-- REMOVED: Embedded admin password update (PP-SEC-007).
-- This migration previously updated the admin password hash in the users table.
-- Admin credentials must now be bootstrapped separately via wrangler CLI or a one-time setup script.
-- No credential-seeding statements remain in any migration.
