-- Seed demo listings

INSERT OR IGNORE INTO listings (id, title, type, property_type, price, price_unit, location, area, city, bedrooms, bathrooms, sqft, parking, description, amenities, images, availability, featured, verified, badge, agent_name, agent_role, agent_phone, agent_avatar, annual_rent, agency_fee, security_deposit, service_charge) VALUES (1, '3-Bedroom Modern Apartment', 'rent', 'apartment', 3500000, '/ year', 'Lekki Phase 1, Lagos', 'Lekki Phase 1', 'Lagos', 3, 2, 1200, 1, 'A well-maintained 3-bedroom apartment in the heart of Lekki Phase 1. The property features spacious living areas, modern kitchen fittings, and secure estate surroundings. Ideal for a family or professionals seeking comfort and convenience.

Annual rent covers the base rent. Move-in costs include agency fees, security deposit (equivalent to one month''s rent), and service charge. All costs are disclosed transparently.', '["24/7 Electricity", "Borehole Water Supply", "Fitted Kitchen", "Built-in Wardrobes", "Secure Estate", "Visitors Parking"]', '["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80"]', 'Immediately', 1, 1, 'Featured', 'Ade Okafor', 'Listing Agent — Lagos', '2348000000001', 'https://randomuser.me/api/portraits/men/32.jpg', 3500000, 350000, 291667, 200000);
INSERT OR IGNORE INTO listings (id, title, type, property_type, price, price_unit, location, area, city, bedrooms, bathrooms, sqft, parking, description, amenities, images, availability, featured, verified, badge, agent_name, agent_role, agent_phone, agent_avatar, annual_rent, agency_fee, security_deposit, service_charge) VALUES (2, '4-Bedroom Detached Duplex', 'sale', 'duplex', 85000000, '', 'Ikeja GRA, Lagos', 'Ikeja GRA', 'Lagos', 4, 3, 2500, 2, 'A stunning 4-bedroom detached duplex in the prestigious Ikeja GRA. This home features spacious en-suite bedrooms, a modern open-plan living area, fully fitted kitchen, and a well-manicured garden. Perfect for a growing family seeking space, security, and convenience in a prime Lagos location.

The property comes with verified title documents, building approvals, and a clean survey plan. Ready for immediate viewing and purchase.', '["En-suite Bedrooms", "Fitted Kitchen", "Garden", "Security Post", "Ample Parking", "Borehole + City Water"]', '["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"]', 'Immediately', 1, 1, 'New', 'Chioma Eze', 'Sales Agent — Lagos', '2348000000002', 'https://randomuser.me/api/portraits/women/44.jpg', NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO listings (id, title, type, property_type, price, price_unit, location, area, city, bedrooms, bathrooms, sqft, parking, description, amenities, images, availability, featured, verified, badge, agent_name, agent_role, agent_phone, agent_avatar, annual_rent, agency_fee, security_deposit, service_charge) VALUES (3, '500 SQM Residential Plot', 'land', 'land', 25000000, '', 'Ibeju-Lekki, Lagos', 'Ibeju-Lekki', 'Lagos', 0, 0, 500, 0, 'A prime 500 SQM residential plot in the rapidly developing Ibeju-Lekki corridor. The land is dry, well-drained, and comes with a registered survey plan and a Certificate of Occupancy (C of O).

Located within proximity to the Lekki Free Trade Zone, Dangote Refinery, and the upcoming international airport. An excellent investment opportunity with strong appreciation potential.', '["C of O Title", "Survey Plan", "Road Access", "Dry Land", "Fenced Perimeter", "No Encumbrances"]', '["https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=1200&q=80"]', 'Immediately', 1, 1, 'Hot Deal', 'Emeka Nnamdi', 'Land Specialist — Lagos', '2348000000003', 'https://randomuser.me/api/portraits/men/45.jpg', NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO listings (id, title, type, property_type, price, price_unit, location, area, city, bedrooms, bathrooms, sqft, parking, description, amenities, images, availability, featured, verified, badge, agent_name, agent_role, agent_phone, agent_avatar, annual_rent, agency_fee, security_deposit, service_charge) VALUES (4, 'Luxury 2-Bedroom Flat', 'rent', 'apartment', 5200000, '/ year', 'Wuse 2, Abuja', 'Wuse 2', 'Abuja', 2, 2, 1100, 1, 'A luxury 2-bedroom flat in the heart of Wuse 2, Abuja''s most sought-after district. The apartment features premium finishes, a modern open-plan kitchen, spacious living area, and 24/7 power supply. Ideal for diplomats, professionals, and small families.

Move-in costs are transparent and include agency fees, security deposit, and service charge.', '["24/7 Electricity", "Premium Finishes", "Fitted Kitchen", "Security", "Parking", "Water Supply"]', '["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80"]', 'Immediately', 0, 0, '', 'Fatima Bello', 'Listing Agent — Abuja', '2348000000004', '', NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO listings (id, title, type, property_type, price, price_unit, location, area, city, bedrooms, bathrooms, sqft, parking, description, amenities, images, availability, featured, verified, badge, agent_name, agent_role, agent_phone, agent_avatar, annual_rent, agency_fee, security_deposit, service_charge) VALUES (5, '5-Bedroom Waterfront Villa', 'sale', 'villa', 150000000, '', 'Victoria Island, Lagos', 'Victoria Island', 'Lagos', 5, 4, 4000, 3, 'An extraordinary 5-bedroom waterfront villa on Victoria Island. This architectural masterpiece offers panoramic water views, a private swimming pool, home automation, and premium finishes throughout. The property includes a guest wing, staff quarters, and a private jetty.

Title documents are verified and the property is ready for immediate transfer.', '["Waterfront", "Private Pool", "Home Automation", "Guest Wing", "Staff Quarters", "Private Jetty"]', '["https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80"]', 'Immediately', 0, 1, '', 'Chioma Eze', 'Sales Agent — Lagos', '2348000000005', 'https://randomuser.me/api/portraits/women/68.jpg', NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO listings (id, title, type, property_type, price, price_unit, location, area, city, bedrooms, bathrooms, sqft, parking, description, amenities, images, availability, featured, verified, badge, agent_name, agent_role, agent_phone, agent_avatar, annual_rent, agency_fee, security_deposit, service_charge) VALUES (6, '300 SQM Plot — Dry Land', 'land', 'land', 8500000, '', 'Epe, Lagos State', 'Epe', 'Lagos', 0, 0, 300, 0, 'A 300 SQM plot of dry, buildable land in Epe, Lagos State. The land is accessible via tarred roads and comes with a registered deed of conveyance. The surrounding area is developing rapidly with new residential estates.

Perfect for first-time land buyers or investors looking for an affordable entry point into the Lagos land market.', '["Deed of Conveyance", "Dry Land", "Tarred Road Access", "Survey Plan", "No Flooding", "Affordable"]', '["https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=1200&q=80"]', 'Immediately', 0, 0, '', 'Emeka Nnamdi', 'Land Specialist — Lagos', '2348000000006', '', NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO listings (id, title, type, property_type, price, price_unit, location, area, city, bedrooms, bathrooms, sqft, parking, description, amenities, images, availability, featured, verified, badge, agent_name, agent_role, agent_phone, agent_avatar, annual_rent, agency_fee, security_deposit, service_charge) VALUES (7, '2-Bedroom Flat — Newly Renovated', 'rent', 'apartment', 1800000, '/ year', 'Surulere, Lagos', 'Surulere', 'Lagos', 2, 1, 900, 0, 'A newly renovated 2-bedroom flat in the vibrant Surulere neighborhood. The apartment has been freshly painted with new tiles, modern plumbing fixtures, and updated electrical wiring. Located close to major roads, markets, and public transport.

An excellent choice for young professionals or small families seeking quality living at an accessible price point.', '["Newly Renovated", "Fitted Kitchen", "Tiled Floors", "Good Location", "Natural Light", "Ventilation"]', '["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80"]', 'Immediately', 0, 0, '', 'Ade Okafor', 'Listing Agent — Lagos', '2348000000007', '', NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO listings (id, title, type, property_type, price, price_unit, location, area, city, bedrooms, bathrooms, sqft, parking, description, amenities, images, availability, featured, verified, badge, agent_name, agent_role, agent_phone, agent_avatar, annual_rent, agency_fee, security_deposit, service_charge) VALUES (8, '4-Bedroom Detached with BQ', 'sale', 'detached', 120000000, '', 'Maitama, Abuja', 'Maitama', 'Abuja', 5, 4, 3200, 3, 'A magnificent 4-bedroom detached house plus a self-contained boys'' quarters in the diplomatic heart of Maitama, Abuja. The property sits on a generous plot with mature landscaping, a private garden, and secure perimeter fencing.

The main house features a grand foyer, formal and family living rooms, a dining area, and a gourmet kitchen. All title documents are verified and current.', '["Boys'' Quarters", "Private Garden", "Grand Foyer", "Gourmet Kitchen", "Security Fencing", "Mature Landscaping"]', '["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"]', 'Immediately', 0, 1, '', 'Fatima Bello', 'Sales Agent — Abuja', '2348000000008', 'https://randomuser.me/api/portraits/men/22.jpg', NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO listings (id, title, type, property_type, price, price_unit, location, area, city, bedrooms, bathrooms, sqft, parking, description, amenities, images, availability, featured, verified, badge, agent_name, agent_role, agent_phone, agent_avatar, annual_rent, agency_fee, security_deposit, service_charge) VALUES (9, '1-Bedroom Self-Contained', 'rent', 'apartment', 1200000, '/ year', 'Yaba, Lagos', 'Yaba', 'Lagos', 1, 1, 550, 0, 'A cozy 1-bedroom self-contained apartment in Yaba, one of Lagos''s most connected neighborhoods. The apartment is WiFi-ready and located within walking distance of the University of Lagos, Yaba College of Technology, and the Yaba tech hub.

Perfect for students, young professionals, or anyone seeking a well-located, affordable rental.', '["WiFi Ready", "Fitted Kitchen", "Good Location", "Near UNILAG", "24/7 Power", "Secure Building"]', '["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80"]', 'Immediately', 0, 0, '', 'Ade Okafor', 'Listing Agent — Lagos', '2348000000009', '', NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO listings (id, title, type, property_type, price, price_unit, location, area, city, bedrooms, bathrooms, sqft, parking, description, amenities, images, availability, featured, verified, badge, agent_name, agent_role, agent_phone, agent_avatar, annual_rent, agency_fee, security_deposit, service_charge) VALUES (10, '450 SQM Corner Plot', 'land', 'land', 18000000, '', 'Gwarinpa, Abuja', 'Gwarinpa', 'Abuja', 0, 0, 450, 0, 'A premium 450 SQM corner plot in Gwarinpa, Abuja''s largest housing estate. The corner position offers dual road access and excellent visibility. The land is fully dry with proper drainage and comes with all title documents.

Gwarinpa is a well-planned estate with good infrastructure, making this an ideal plot for residential development or investment.', '["Corner Position", "Dual Road Access", "Title Documents", "Dry Land", "Good Drainage", "Well-Planned Estate"]', '["https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80"]', 'Immediately', 0, 0, '', 'Emeka Nnamdi', 'Land Specialist — Abuja', '2348000000010', '', NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO listings (id, title, type, property_type, price, price_unit, location, area, city, bedrooms, bathrooms, sqft, parking, description, amenities, images, availability, featured, verified, badge, agent_name, agent_role, agent_phone, agent_avatar, annual_rent, agency_fee, security_deposit, service_charge) VALUES (11, '3-Bedroom Luxury Terrace', 'sale', 'terrace', 95000000, '', 'Asokoro, Abuja', 'Asokoro', 'Abuja', 3, 3, 2000, 2, 'A beautifully designed 3-bedroom luxury terrace house in the exclusive Asokoro district of Abuja. Part of a small gated community, the property offers modern architecture, high-quality finishes, and a private garden terrace.

Asokoro is one of Abuja''s most secure and prestigious neighborhoods, home to diplomats, government officials, and business leaders.', '["Gated Estate", "Private Terrace", "Modern Architecture", "High-Quality Finishes", "24/7 Security", "Club House Access"]', '["https://images.unsplash.com/photo-1464082354059-27db6ce50048?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"]', 'Immediately', 0, 1, '', 'Fatima Bello', 'Sales Agent — Abuja', '2348000000011', '', NULL, NULL, NULL, NULL);
INSERT OR IGNORE INTO listings (id, title, type, property_type, price, price_unit, location, area, city, bedrooms, bathrooms, sqft, parking, description, amenities, images, availability, featured, verified, badge, agent_name, agent_role, agent_phone, agent_avatar, annual_rent, agency_fee, security_deposit, service_charge) VALUES (12, '2-Bedroom Serviced Apartment', 'rent', 'apartment', 2400000, '/ year', 'Ajah, Lagos', 'Ajah', 'Lagos', 2, 2, 1000, 1, 'A modern 2-bedroom serviced apartment in the fast-growing Ajah district of Lagos. The apartment features a swimming pool, gym, and 24/7 security. Located close to the Lekki-Epe Expressway for easy commuting.

Serviced apartments in this complex offer a hassle-free living experience with professional property management.', '["Swimming Pool", "Fitness Gym", "24/7 Security", "Property Management", "Parking", "Water Supply"]', '["https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80"]', 'Immediately', 0, 0, '', 'Ade Okafor', 'Listing Agent — Lagos', '2348000000012', '', NULL, NULL, NULL, NULL);